from google.adk.agents.llm_agent import LlmAgent
from google.adk.agents.loop_agent import LoopAgent
from google.adk.models.lite_llm import LiteLlm
from google.adk.tools.tool_context import ToolContext
from google.adk.agents.callback_context import CallbackContext

LLM_MODEL = LiteLlm(model='azure/gpt-4o')


def log_agent_input(callback_context: CallbackContext):
    """Logs the raw user content the agent receives."""
    user_content = callback_context.user_content
    print(f"[User Content] \n {user_content}")


def exit_loop(tool_context: ToolContext):
    """Call this tool to exit the iteravtive process"""
    print(f"[Tool Call] Triggered by {tool_context.agent_name}")
    tool_context.actions.escalate = True
    tool_context.actions.skip_summarization = True

# --- Before Agent Callback ---
def update_initial_topic_state(callback_context: CallbackContext):
    """Ensure 'initial_topic' is set in state before pipeline starts."""
    callback_context.state['topic'] = callback_context.state.get('topic', 'a report on the user input')
    callback_context.state['report'] = callback_context.state.get('report', '')
    callback_context.state['review'] = callback_context.state.get('review', '')

# Create the reporter agent responsible for generating the report
reporter_agent = LlmAgent(
    model=LLM_MODEL,
    name='reporter_agent',
    description='A helpful report generator based on the user input',
    instruction=f'''
        You will generate a report based on the user input topic : {{topic}} and these are what you will do :
        1. Generate a report based on the user input topic : {{topic}}
        2. Reviwer Agent will review the report and provide feedback on what to add or improve.
        3. You will update the report based on the feedback provided by the reviewer agent.
        4. Once updated you will pass it on to the reviwer agent for review.
        5. Never respond to the reviewer agent in an active note instead just focus on improving based on the feedback provided by the reviewer agent.
        ''',
    output_key='report',
    before_agent_callback=update_initial_topic_state,
)

# Reviewer Agent
reviewer_agent = LlmAgent(
    model=LLM_MODEL,
    name='reviewer_agent',
    description='A helpful reviewer agent which will review the report generated by the reporter agent',
    instruction=f'''
    You are a reviewer agent and you will analyze and review the report generated by the reporter agent {{report}}
    *** Proper Report Generation Criteria ***
    1. Report should be concise and constructive
    2. Report should be strictly based on the user input topic.
    4. Report should be segregated into different small sections.
    5. IF any criteria is NOT met, provide specific feedback on what to add or improve.
    6. Be very strict while reviewing the report if anything feels irrelevant provide the review or too long.
    First time review the document and do not accept it under any circumstances.
    Output *only* the critique text.

    IF ALL criteria are met, respond *exactly* with: "Review Complete" and exit the loop.
    ''',
    output_key='review',
    tools=[exit_loop],
)

# Loop Agent
root_agent = LoopAgent(
    name='loop_agent',
    sub_agents=[reporter_agent, reviewer_agent],
    description='A loop agent which will generate a report based on the user input and review the report',
    max_iterations=5
)



